name: Deployment

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

  workflow_dispatch:

jobs:
  push_to_DockerHub_Dotnet_Core:
    name: Push Images to DockerHub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build Docker image and push to docker hub
    
    # only if the app build and test successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: OurNonfictionBackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/el-proyecte-grande-backend:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/el-proyecte-grande-backend:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
            
  push_to_DockerHub_React:
    name: Push Images to DockerHub React
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build Docker image and push to docker hub
    
    # only if the app build and test successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: OurNonfictionFrontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/el-proyecte-grande:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/el-proyecte-grande:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}