name: Test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    name: Build & Test App
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0' ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  testing_react_app:        
    name: Lint
    on:
      workflow_run:
        workflows: ["Test"]
        types:
          - completed

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
    jobs:
      # This workflow contains multiple jobs
      build_test:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Build & Test App
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v3

          - name: setup node
            uses: actions/setup-node@master
            with:
              node-version: ${{ matrix.node-version }}

          # install application dependencies
          - name: Install dependencies
            run: |
              npm install
              npm ci
          # build and test the apps
          - name: test
            run: |
              npm run lint      
